Repository janeljs/java-was, pull requests merged in 2021-03, with the labels that each got.

#14 feat : 미션 1-5 로그인 성공 여부에 따라 cookie값 설정
  src/main/java/webserver/RequestHandler.java
  webapp/user/form.html
  webapp/user/login.html
Labels: mission

#18 refactor: RequestHandler의 책임을 HttpRequest와 HttpResponse로 분리
  src/main/java/webserver/HttpMethod.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/RequestHandler.java
Labels: mission

#19 2단계 리팩토링 가이드 추가
  README.md
Labels: documentation

#23 HttpRequest, HttpResponse 리팩토링
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponse.java
  src/test/java/webserver/HttpRequestTest.java
  src/test/resources/Http_Forward.txt
  src/test/resources/Http_POST2.txt
Labels: enhancement
